# roles/dnsmasq/tasks/main.yml
---
- name: Install Dnsmasq
  package:
    name: dnsmasq
    state: present
  tags: dnsmasq

- name: Set configuration file
  dnsmasq_domain_needed: false
  dnsmasq_bogus_priv: true
  dnsmasq_authoritative: false
  dnsmasq_expand_hosts: false
  template:
    src: dnsmasq_conf.j2
    dest: /etc/dnsmasq.conf
    validate: 'dnsmasq --test --conf-file=%s'
  notify: restart dnsmasq
  tags: dnsmasq

- name: Make sure Dnsmasq is running
  service:
    name: dnsmasq
    state: started
    enabled: yes
  tags: dnsmasq
